version: '3'

services:
  node1:
    image: indieproof/knockoutcoin
    container_name: knockouttest-node1
    volumes:
      - ../KnockoutCoind:/var/lib/KnockoutCoind/
    networks:
      testnet:
        ipv4_address: 172.16.76.11
  
#  node2:
#    image: indieproof/knockoutcoin
#    container_name: knockouttest-node2
#    networks:
#      testnet:
#        ipv4_address: 172.16.76.12
  
#  node3:
#    image: indieproof/knockoutcoin
#    container_name: knockouttest-node3
#    networks:
#      testnet:
#        ipv4_address: 172.16.76.13

networks:
  testnet:
    ipam:
      config:
        - subnet: 172.16.76.0/24

